import { Button, Text, Loader } from "@mantine/core";
import { IconSparkles, IconRefresh } from "@tabler/icons-react";
import { motion, AnimatePresence } from "framer-motion";
import { useAISummary } from "../hooks/useAISummary";
import { SectionHeading } from "./SectionHeading";
import classes from "./AISummarySection.module.css";

export function AISummarySection() {
  const { summary, loading, error, generate, reset } = useAISummary();

  return (
    <section className={classes.section} id="ai-summary">
      <div className={classes.inner}>
        <SectionHeading index="04" title="AI Portfolio Summary" />

        <div className={classes.card}>
          <div className={classes.cardTop}>
            <div className={classes.cardInfo}>
              <Text className={classes.cardTitle}>Generate my summary</Text>
              <Text className={classes.cardSub}>
                Uses Claude AI to craft a personalized, first-person narrative based on my full background.
              </Text>
            </div>

            <div className={classes.actions}>
              {!summary && !loading && (
                <Button
                  leftSection={<IconSparkles size={15} stroke={1.5} />}
                  onClick={generate}
                  className={classes.generateBtn}
                  variant="filled"
                  size="sm"
                >
                  Generate with AI
                </Button>
              )}
              {(summary || error) && !loading && (
                <Button
                  leftSection={<IconRefresh size={14} stroke={1.5} />}
                  onClick={() => { reset(); setTimeout(generate, 100); }}
                  variant="subtle"
                  size="sm"
                >
                  Regenerate
                </Button>
              )}
            </div>
          </div>

          <AnimatePresence mode="wait">
            {loading && (
              <motion.div
                key="loading"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className={classes.loadingState}
              >
                <Loader size="sm" color="teal" type="dots" />
                <Text size="sm" c="dimmed">Claude is reading your resume…</Text>
              </motion.div>
            )}

            {error && !loading && (
              <motion.div
                key="error"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className={classes.errorState}
              >
                <Text size="sm" c="red">{error}</Text>
              </motion.div>
            )}

            {summary && !loading && (
              <motion.div
                key="summary"
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.4, ease: [0.22, 1, 0.36, 1] }}
                className={classes.summaryText}
              >
                {summary.split("\n\n").map((para, i) => (
                  <p key={i} className={classes.para}>{para}</p>
                ))}
                <div className={classes.generatedBadge}>
                  <IconSparkles size={11} stroke={1.5} />
                  <span>Generated by Claude AI</span>
                </div>
              </motion.div>
            )}

            {!summary && !loading && !error && (
              <motion.div
                key="idle"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className={classes.idleState}
              >
                <Text size="sm" c="dimmed" ta="center">
                  Hit the button above to generate a unique portfolio summary using Claude AI.
                </Text>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </section>
  );
}
